format = """
$username$hostname$shlvl$directory\
$git_branch$git_commit$git_state$git_status$hg_branch\
$kubernetes$docker_context$aws$gcloud$package\
$cmd_duration$line_break\
$cmake$dart$dotnet$elixir$elm$erlang$golang$helm$java$julia$nim$nodejs$ocaml\
$perl$php$purescript$python$ruby$rust$swift$terraform$zig$nix_shell$conda\
$env_var$crystal\
$jobs$character\
"""
add_newline = false
scan_timeout = 10

[username]
format = "[$user]($style)"
[hostname]
format = "@[$hostname]($style) "
[git_branch]
format = "[$symbol$branch]($style) "
[package]
display_private = "true"
symbol = "ï£– "
format = "[$symbol$version]($style) "
[cmd_duration]
format = "[$duration]($style) "

[aws]
symbol = "î­ "
format = "[$symbol$profile(\\($region\\))]($style) "
disabled = true
[docker_context]
symbol = "î° "
format = "[$symbol$context]($style) "
disabled = true
[gcloud]
symbol = "î² "
format = "[$symbol$active(\\($region\\))]($style) "
disabled = true
[cmake]
symbol = "ï›"
format = "[$symbol$version]($style) "
[conda]
symbol = "ğŸ…’ "
format = "[$symbol$environment]($style) "
[crystal]
symbol = "CRYSTAL: "
format = "[$symbol$version]($style) "
[dart]
symbol = "î˜ "
format = "[$symbol$version]($style) "
[dotnet]
symbol = "î¿ "
[elixir]
symbol = "î˜­ "
format = "[$symbol$version \\(OTP $otp_version\\)]($style) "
[elm]
symbol = "î˜¬ "
format = "[$symbol$version]($style) "
[erlang]
symbol = "î± "
format = "[$symbol$version]($style) "
[golang]
symbol = "îœ¤ "
format = "[$symbol$version]($style) "
[helm]
symbol = "âˆ "
format = "[$symbol$version]($style) "
[java]
symbol = "îœ¸ "
format = "[${symbol}${version}]($style) "
[julia]
symbol = "î˜¤ "
format = "[$symbol$version]($style) "
[nim]
symbol = "NIM: "
format = "[$symbol$version]($style) "
[nodejs]
symbol = "îœ˜ "
format = "[$symbol$version]($style) "
[ocaml]
symbol = "OCAML: "
format = "[$symbol$version]($style) "
[perl]
symbol = "î© "
format = "[$symbol$version]($style) "
[php]
symbol = "îœ½ "
format = "[$symbol$version]($style) "
[python]
symbol = "îœ¼ "
format = "[${symbol}${version}( \\($virtualenv\\))]($style) "
[ruby]
symbol = "îœ¹ "
format = "[$symbol$version]($style) "
[rust]
symbol = "î¨ "
format = "[$symbol$version]($style) "
[swift]
symbol = "î• "
format = "[$symbol$version]($style) "
[zig]
symbol = "â†¯ "
format = "[$symbol$version]($style) "
[purescript]
symbol = "<=> "
format = "[$symbol$version]($style) "
